checkItmName recursively & reject resource with $.ext
nodeSolidServer/node-solid-server pull request #1726
Opened 2023-03-29 15:11 UTC by bourgeoa

2023-03-29 17:01 UTC, TallTed commented on lib/ldp.js
> +      // item do not exist, check one level up the tree
```suggestion
      // item does not exist, check one level up the tree
```

2023-04-03 18:13 UTC, bourgeoa commented
@michielbdejong 
The new code was missing the fact that it needed to check the % encoded $
Tested locally and it is now working as expected.
I'm not sure of the error code used 400 and not 500 (server decision) ? This is not a solid specification.

Samely I am not sure with error 404 error code rejecting same name for documentResource and container, but here it is a solid protocol spec

2023-04-03 19:41 UTC, TallTed requested changes
Better to use `percent-encoded` wording than `% encoded` symbol shorthand.

I'm not so sure about `$` vs `dollar-sign-extension` or `dollar-extension`, so I'm leaving those unchanged.

I'm open to embellishing by including the `$` and/or `%` symbol(s) *with* the words.

2023-04-03 19:41 UTC, TallTed commented on lib/ldp.js
> +    // reject resource with % encoded $ extension
```suggestion
    // reject resource with percent-encoded $ extension
```

2023-04-03 19:41 UTC, TallTed commented on test/integration/http-test.js
> +    it('should not create a resource with % encoded $.ext', function (done) {
```suggestion
    it('should not create a resource with percent-encoded $.ext', function (done) {
```

2023-04-06 12:34 UTC, timea-solid approved these changes
Why should I not be able to create a resource with same name as container?

2023-04-06 13:30 UTC, merged