update check itemName
nodeSolidServer/node-solid-server pull request #1748
Opened 2023-12-26 11:55 UTC by bourgeoa

2023-12-26 16:02 UTC, TallTed requested changes
small stuff, for humans

2023-12-26 16:02 UTC, TallTed commented on lib/handlers/put.js
> +  // check if a folder or resource with same name exists
```suggestion
  // check whether a folder or resource with same name exists
```

2023-12-26 16:02 UTC, TallTed commented on lib/ldp.js
> +    // allways return a valid URL.
```suggestion
    // always return a valid URL.
```

2023-12-26 16:02 UTC, TallTed commented on lib/ldp.js
> +  // check if a document (or container) has the same name than a document (or container)
```suggestion
  // check whether a document (or container) has the same name as another document (or container)
```

2023-12-26 16:02 UTC, TallTed commented on lib/ldp.js
> +      // check resource exists
```suggestion
      // check whether resource exists
```

2023-12-26 16:02 UTC, TallTed commented on lib/ldp.js
> +        // check resource with same name exists
```suggestion
        // check whether resource with same name exists
```

2023-12-27 11:14 UTC, bourgeoa commented
> small stuff, for humans

Thanks. You are indeed very helpful for humans, that we still are ...

2024-02-05 18:44 UTC, bourgeoa commented
merged with https://github.com/nodeSolidServer/node-solid-server/pull/1750

2024-02-05 18:44 UTC, closed without merging