5.7.9 beta
nodeSolidServer/node-solid-server pull request #1750
Opened 2024-01-10 22:20 UTC by bourgeoa

2024-01-11 17:12 UTC, TallTed requested changes
trivial

2024-01-11 17:12 UTC, TallTed commented on README.md
> +By default `solid` runs in debug all mode. To stop the debug logs use `-q`, the quiet parameter.
```suggestion
By default, `solid` runs in `debug all` mode. To stop the debug logs, use `-q`, the quiet parameter.
```

2024-01-11 17:12 UTC, TallTed commented on README.md
> +
```suggestion
# DEBUG="solid:ACL" logs only debug.ACL's
```

2024-01-16 17:43 UTC, TallTed submitted a review, later dismissed
minor, for humans

2024-01-16 17:43 UTC, TallTed commented on lib/acl-checker.js
> +        // then Read Write from parent is required
```suggestion
        // then both Read and Write on parent is required
```

2024-01-16 17:43 UTC, TallTed commented on lib/acl-checker.js
> +  // Gets the ACL's that applies to the resource
```suggestion
  // Gets any ACLs that apply to the resource
```

2024-02-06 10:40 UTC, michielbdejong approved these changes

2024-02-06 18:57 UTC, merged